CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

# Shell needs a bit more stack/heap than the defaults on a 16 KB SRAM part
CONFIG_MAIN_STACK_SIZE=2048
